# Generated by Django 6.0 on 2025-12-12 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Egreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('n_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_transferencia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descripcion_movimiento', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.clasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('n_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('monto_transferencia', models.DecimalField(decimal_places=2, max_digits=15)),
                ('descripcion_movimiento', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('centro_costo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.centrocosto')),
                ('clasificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.clasificacion')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.empresa')),
            ],
        ),
    ]
