# Generated by Django 6.0 on 2025-12-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaChica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.IntegerField()),
                ('responsable', models.CharField(max_length=100)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('negocio', models.CharField(help_text='Ej: Compra de insumos, Taxi, etc.', max_length=100)),
                ('tipo_documento', models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta'), ('PEAJE', 'Peaje'), ('OTRO', 'Otro Documento')], default='BOLETA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
