# Generated by Django 6.0 on 2025-12-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cajachica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cajachica',
            options={'verbose_name_plural': 'Caja Chica'},
        ),
        migrations.RemoveField(
            model_name='cajachica',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='cajachica',
            name='negocio',
        ),
        migrations.AddField(
            model_name='cajachica',
            name='descripcion',
            field=models.TextField(default='', verbose_name='Descripción del Gasto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cajachica',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cajachica',
            name='monto',
            field=models.IntegerField(verbose_name='Monto Gasto'),
        ),
        migrations.AlterField(
            model_name='cajachica',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA', 'Factura'), ('BOLETA', 'Boleta'), ('PEAJE', 'Peaje'), ('VALE', 'Vale / Recibo'), ('OTRO', 'Otro Documento')], default='BOLETA', max_length=20),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='monto_transferencia',
            field=models.IntegerField(verbose_name='Monto Transferencia'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='monto_transferencia',
            field=models.IntegerField(verbose_name='Monto Transferencia'),
        ),
    ]
