# Generated by Django 6.0 on 2025-12-18 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cajachica_options_remove_cajachica_comentario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=20)),
                ('cargo', models.CharField(max_length=100)),
                ('fecha_contrato', models.DateField(blank=True, null=True)),
                ('fecha_finiquito', models.DateField(blank=True, null=True)),
                ('monto_finiquito', models.IntegerField(default=0)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
    ]
