# Generated by Django 6.0 on 2025-12-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_perfil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingreso',
            old_name='tipo',
            new_name='tipo_documento',
        ),
        migrations.AddField(
            model_name='ingreso',
            name='iva',
            field=models.IntegerField(default=0, verbose_name='Monto IVA'),
        ),
    ]
