# Generated by Django 6.0 on 2025-12-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_tipo_ingreso_tipo_documento_ingreso_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajachica',
            name='monto',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Monto Gasto'),
        ),
        migrations.AlterField(
            model_name='egreso',
            name='monto_transferencia',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Monto Transferencia'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='iva',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Monto IVA'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='monto_transferencia',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Monto Transferencia'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='monto_finiquito',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
