# Generated by Django 6.0 on 2025-12-27 12:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cargo_trabajador_estado_alter_trabajador_rut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso')], max_length=10)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('monto', models.IntegerField()),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco / Cuenta')),
                ('n_documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('centro_costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.centrocosto')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Movimiento Financiero',
                'verbose_name_plural': 'Movimientos Financieros',
                'ordering': ['-fecha'],
            },
        ),
    ]
