# Generated by Django 6.0 on 2025-12-27 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_movimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código SKU')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_minimo', models.IntegerField(default=10, verbose_name='Alerta Stock Bajo')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50)),
                ('fecha_elaboracion', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('cantidad', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
            options={
                'ordering': ['fecha_vencimiento'],
            },
        ),
    ]
