# Generated by Django 6.0 on 2025-12-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_producto_lote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='estado',
            field=models.CharField(blank=True, default='PAGADO', max_length=50, null=True),
        ),
    ]
